apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-master-pvc  #claimName
  labels:
    app: jenkins-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi