---

tasks:
- import_tasks: 'basic-hardening.yml'
- import_tasks: 'editors-pkg.yml'
- import_tasks: 'network-pkg.yml'
- import_tasks: 'repo-setup.yml'
- import_tasks: 'security-pkg.yml'
- import_tasks: 'system-pkg.yml'
