---

- name: 'Simian Army for Ubuntu'
  user: 'ubuntu'
  vars_files:
    - ../vars/{{ ansible_distribution }}.yml

  hosts: 'all'
  roles:
    - role: 'base'
      tags: 'base'

    - role: 'tomcat'
      tags: 'tomcat'

    - role: 'simian_army'
      tags: 'simian_army'
